#include <iostream>
#include <random>
using namespace std;

int main()
{
    random_device seed;
    mt19937 generator( seed() );

    uniform_int_distribution<> number_Generator(1,6);
    int num = number_Generator(generator);

    cout << "Random Number form 1-6 : " << num << endl;

    return 0;
}

/*

formal definition of seed: a number that is used to initialize the pseudo-random number generator (PRNG).
it defines the starting point of the random number generation process

well everybody you are looking at this and thinking WHAT IS THIS?????
fear not your friendly nighbourhood programmer is here

ok you know i told you there is no true random in computing
it is kinda atrue and kinda false but to put it simply

on line 7 :

i)
on your PC there is an Operating System (OS)
that OS have an entropy calculating API which gives true random seed to us
it is calculated by various methods and there are many APIs

ii)
for e.g: Windows's CryptoAPI uses the binary registry key 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\RNG\Seed 
to store a seeded value from all of its entropy sources.

iii)
this method is slow but it gives true random seed to us to plug in our pseudo-random generator
see this is the reason it is kinda random

so now if you understand this you will understand what this line means

iv)
random_device requests the OS to give it a random seed
then when device() is called it haves a true random seed to feed in the generator

on line 8 :

we create a Mersenne Twister 19937 pseudo-random generator which will take the
seed calculated by device() and give us a random number
now our generator() is seeded and on to the next step

on line 10 :

uniform_int_distribution<> creates a range between 1-6 (inclusive) and is stored in number_Generator
this range have equal chance of variable apppering (for beginners)

uniform_int_distribution<> compresses the number given by engine and compress it to your range it have
a huge process behind it and i don't recommend you to dive deeply for now

on line 11 :

we use number_Generator(generator)

here we will take a value at index generator in range number_Generator
to put it simply
the seed generated from line 7 and selects the value in the range generated by number_Generator

then we do whatever we want
remember this method is slow af hence i urge beginners to use the basic random generator as it is fast
and you will not use this in random number generator for dice 😏
why?
due to the unforseen circumstances created by AI (in boomer voice) your assignment graded by teacher
using AI grader will flag it as AI and you will get SUPER F like timmy turner in your tests

*/